version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:21-jdk
      - image: cimg/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in `seq 1 30`; do
              nc -z localhost 3306 && echo "MySQL is up" && break
              echo "Waiting for MySQL..."
              sleep 1
            done
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run Tests
          command: mvn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
