version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
      - image: cimg/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bookstore
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in `seq 1 30`; do
              if echo 'SELECT 1' | mysql -h 127.0.0.1 -u root --protocol=tcp; then
                echo "MySQL is ready"
                break
              fi
              echo "Waiting for MySQL..."
              sleep 1
            done
      - run:
          name: Create Database
          command: |
            mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE IF NOT EXISTS bookstore;'
      - run:
          name: Install Dependencies
          command: mvn dependency:resolve
      - run:
          name: Run Tests
          command: mvn test
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/bookstore
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
