version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
      - image: circleci/mysql:5.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in `seq 1 30`; do
              if echo 'SELECT 1' | mysql -h 127.0.0.1 -u root --protocol=tcp; then
                echo "MySQL is ready"
                break
              fi
              echo "Waiting for MySQL..."
              sleep 1
            done
      - run:
          name: Create test database
          command: echo 'CREATE DATABASE IF NOT EXISTS testdb;' | mysql -h 127.0.0.1 -u root --protocol=tcp
      - run:
          name: Install Dependencies
          command: mvn dependency:resolve
      - run:
          name: Run Tests
          command: mvn test
    environment:
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: ""

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
